[tool.poetry]
name = "hello-python"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
invoke = "^2.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
